
SELECT 
	NOMBRE_MASTER,
	#DISTRIBUIDOR,
	MUNICIPIO,
	TIPO_ACTIVACION,
	SUM(ACTIVADAS_TOTAL) AS Unidades,
	CASE
		WHEN NOMBRE_MASTER IN ('DESARROLLO LOCAL E INTEGRADORSA DE CV', 'GITTSA TELECOM, S.A. DE C.V.', 'COMERCIALIZADORA SANCHEZ TAGLES.A. DE C.V.', 'SEÑAL SATELITE SA DE CV', 'TDA TELECOMUNICACIONES, S.A. DE C.V', 'TV CODICE, S.A. DE C.V.', 'VANGUARDIA SATELITAL S.A. DE C.V.')
             AND TIPO_ACTIVACION LIKE 'pospago%' THEN CAST(SUM(ACTIVADAS_TOTAL) * 300 AS VARCHAR(50))
        WHEN NOMBRE_MASTER IN ('DESARROLLO LOCAL E INTEGRADORSA DE CV', 'GITTSA TELECOM, S.A. DE C.V.', 'COMERCIALIZADORA SANCHEZ TAGLES.A. DE C.V.', 'SEÑAL SATELITE SA DE CV', 'TDA TELECOMUNICACIONES, S.A. DE C.V', 'TV CODICE, S.A. DE C.V.', 'VANGUARDIA SATELITAL S.A. DE C.V.')
             AND TIPO_ACTIVACION LIKE 'prepago%' THEN CAST(SUM(ACTIVADAS_TOTAL) * 200 AS VARCHAR(50))
		WHEN NOMBRE_MASTER IN ('CUEVAS GONZALEZ VICTOR HUGO', 'RAMIRO CARRERA ANTONIO', 'CONSULTORIA SILVA BERLANGA, S. DE R.L. DE C.V.', 'SERVICIOS Y COMUNICACIONES MALDONADO SA DE CV', 'SAUCEDA HERNANDEZ EDDY ANGEL', 'OSUNA ARANDA BLANCA PATRICIA', 'GALAVIZ ABELAR JORGE LUIS','CASANOVA MARTINEZ ALEJANDRO','GOBETEL S.A DE C.V.','CAMARA BERNAL JESUS','LAZARO FUENTES HISSY ESTELA','ARREGOYTIA WINZIG MAURICIO','TAMAYO ESQUIVEL CLAUDIA VERONICA','HERNANDEZ ACOLTZI FABIOLA','ESPINOSA PELAYO EDGAR OMAR','GARCIA SALAZAR CLAUDIA','MIRANDA CARDENASRUBEN','PEREZ GALINDO EDITH MONICA','SANCHEZ CORTAZAR SOCORRO','TERAN FLORES LUCERO MAHARAI','FLORES RUIZ VICTOR HUGO','VERA NOGUÉZ ROBERTO','ORTEGA LORENZO TOMASA','OVIEDO CARDENAS JOSE LUIS','JIMENEZ MALTA JOSE ARMANDO','TORRES HERNÁNDEZ JOEL')
             AND TIPO_ACTIVACION LIKE 'pospago%' THEN CAST(SUM(ACTIVADAS_TOTAL) * 150 AS VARCHAR(50))
        WHEN NOMBRE_MASTER IN ('CUEVAS GONZALEZ VICTOR HUGO', 'RAMIRO CARRERA ANTONIO', 'CONSULTORIA SILVA BERLANGA, S. DE R.L. DE C.V.', 'SERVICIOS Y COMUNICACIONES MALDONADO SA DE CV', 'SAUCEDA HERNANDEZ EDDY ANGEL', 'OSUNA ARANDA BLANCA PATRICIA', 'GALAVIZ ABELAR JORGE LUIS','CASANOVA MARTINEZ ALEJANDRO','GOBETEL S.A DE C.V.','CAMARA BERNAL JESUS','LAZARO FUENTES HISSY ESTELA','ARREGOYTIA WINZIG MAURICIO','TAMAYO ESQUIVEL CLAUDIA VERONICA','HERNANDEZ ACOLTZI FABIOLA','ESPINOSA PELAYO EDGAR OMAR','GARCIA SALAZAR CLAUDIA','MIRANDA CARDENASRUBEN','PEREZ GALINDO EDITH MONICA','SANCHEZ CORTAZAR SOCORRO','TERAN FLORES LUCERO MAHARAI','FLORES RUIZ VICTOR HUGO','VERA NOGUÉZ ROBERTO','ORTEGA LORENZO TOMASA','OVIEDO CARDENAS JOSE LUIS','JIMENEZ MALTA JOSE ARMANDO','TORRES HERNÁNDEZ JOEL')
             AND TIPO_ACTIVACION LIKE 'prepago%' THEN CAST(SUM(ACTIVADAS_TOTAL) * 100 AS VARCHAR(50))
        ELSE 'Revisar'
    END AS Importe
FROM Detalle_Pago_Bonos_Geografico
WHERE SEMANA = 'Semana del 17 al 23 de 06-2024'
GROUP BY NOMBRE_MASTER, #DISTRIBUIDOR, MUNICIPIO, TIPO_ACTIVACION;